FROM webhippie/alpine:latest-arm@sha256:3e3cc7a798fc86f8845422f425d1f0aff996be568eacb33fd1a7b921ba2ee799

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add tzdata git build-base libffi-dev libxml2-dev libxslt-dev openssl-dev ruby-dev ruby ruby-bundler ruby-rake ruby-io-console ruby-bigdecimal ruby-irb ruby-rdoc ruby-minitest ruby-json ruby-etc && \
  bundle config build.nokogiri --use-system-libraries && \
  rm -rf /var/cache/apk/*
