FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:147c30af4d302c2e4f1bd6afd0f27fc0796d160795a436fa6641264512beb2f8

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add tzdata git build-base libffi-dev libxml2-dev libxslt-dev openssl-dev ruby-dev ruby ruby-bundler ruby-rake ruby-bigdecimal ruby-rdoc ruby-minitest && \
  bundle config build.nokogiri --use-system-libraries && \
  rm -rf /var/cache/apk/*
