FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:8c64c1be1746192a96a6fb0eeaa9ae22f0eb07030edeed35cfce269190ee7281

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add tzdata git build-base libffi-dev libxml2-dev libxslt-dev openssl-dev ruby-dev ruby ruby-bundler ruby-rake ruby-bigdecimal ruby-rdoc ruby-minitest && \
  bundle config build.nokogiri --use-system-libraries && \
  rm -rf /var/cache/apk/*
