FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:186cfab6fe45db91ce80ce4a86729a9f47db6e08afeb3805c74e29c59ed62b81

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add tzdata git build-base libffi-dev libxml2-dev libxslt-dev openssl-dev ruby-dev ruby ruby-bundler ruby-rake ruby-bigdecimal ruby-rdoc ruby-minitest && \
  bundle config build.nokogiri --use-system-libraries && \
  rm -rf /var/cache/apk/*
