FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:3654fee32bf6e7801421abec274f7440067db343562634d3ab0424b35dc1a459

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add tzdata git build-base libffi-dev libxml2-dev libxslt-dev openssl-dev ruby-dev ruby ruby-bundler ruby-rake ruby-bigdecimal ruby-rdoc ruby-minitest && \
  bundle config build.nokogiri --use-system-libraries && \
  rm -rf /var/cache/apk/*
