FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:e9853aa23cf4ad58e922decc6268a4e3a5626f2f973ef876550c9c27e9fd077c

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add tzdata git build-base libffi-dev libxml2-dev libxslt-dev openssl-dev ruby-dev ruby ruby-bundler ruby-rake ruby-bigdecimal ruby-rdoc ruby-minitest && \
  bundle config build.nokogiri --use-system-libraries && \
  rm -rf /var/cache/apk/*
