FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:c778aebac9177eb9d4f3d7baad5ee89e60d3e423797feb6dcd5a5cd88e6be16d

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add tzdata git build-base libffi-dev libxml2-dev libxslt-dev openssl-dev ruby-dev ruby ruby-bundler ruby-rake ruby-io-console ruby-bigdecimal ruby-irb ruby-rdoc ruby-minitest ruby-json ruby-etc && \
  bundle config build.nokogiri --use-system-libraries && \
  rm -rf /var/cache/apk/*
